version: "3"
services:
  redis:
    image: redis:7.0.4-alpine3.16
    container_name: redis
    restart: always
    ports:
      - 6379:6379
  app:
    env_file:
      - .env_docker
    build: ./notificationdrf
    command: bash -c "
              python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000
      "
    container_name: app
    depends_on:
      - redis
    volumes:
      - .:/code
    ports:
      - 8000:8000
  celery:
    env_file:
      - .env_docker
    build: ./notificationdrf
    command: python -m celery -A notificationdrf worker -l info --purge -P eventlet
    volumes:
      - .:/code
    depends_on:
      - redis
      - app
  celery-beat:
    env_file:
      - .env_docker
    build: ./notificationdrf
    command: python -m celery -A notificationdrf beat -l INFO
    volumes:
      - .:/code
    depends_on:
      - redis
      - app
      - celery